ALTER TABLE "Ticket" ADD COLUMN "hourlyRate" DOUBLE PRECISION;
ALTER TABLE "Ticket" ADD COLUMN "fixedPrice" DOUBLE PRECISION;
ALTER TABLE "Ticket" ADD COLUMN "showPrice" BOOLEAN NOT NULL DEFAULT false;
